signalmaster:
  image: yfix/signalmaster
#  build: .
  restart: always
  ports:
    - "127.0.0.1:8888:8888"
  environment:
    - NODE_ENV=production
  volumes:
    - ./server.js:/app/server.js
    - ./src:/app/src
    - ./scripts:/app/scripts
    - ./config:/app/config
